Initial preparation for v6.0
packbackbooks/lti-1-3-php-library pull request #105
Opened 2023-10-04 03:26 UTC by dbhynds

## Summary of Changes

Marks several objects for deprecation in the next major release. All of these methods are from the original library before we took it over. They don't follow modern PHP paradigms.

## Testing

- [ ] I have added automated tests for my changes
- [ ] I ran `composer test` before opening this PR
- [ ] I ran `composer lint-fix` before opening this PR

2023-10-04 13:46 UTC, lin-brian-l commented
@dbhynds sorry, I'm lacking some context - can you explain what we're going to change in v6.0 and why we can remove those functions?

2023-10-06 14:42 UTC, dbhynds commented on src/ImsStorage/ImsCache.php
> + */
Both of these classes are leftover from the old library. I left them in originally as examples, but frankly, they're a mess and won't really function in a modern web app. I'd rather leave it up to people to create their own implementations.

2023-10-06 14:44 UTC, dbhynds commented on src/JwksEndpoint.php
> +     * @deprecated
It's really just a bad idea in general to `echo` anything out in a modern php app. If someone needs to echo out the json payload, it should be easy enough for them to just write the code on line 58 themselves in their app.

2023-10-06 14:45 UTC, dbhynds commented on src/LtiDeepLink.php
> +     * @deprecated
Once again, we shouldn't echo anything. Also... why are we building this form for people? They can't style it. If they need a form like this, they should build it themselves.

2023-10-06 14:46 UTC, dbhynds commented on src/LtiGrade.php
> +     * @todo: Deprecate this in the next major version
I'm not certain about this one. Talking to Matt to see if this is something we actually want to do or not.

2023-10-09 14:51 UTC, lin-brian-l submitted a review, later dismissed

2023-12-04 22:43 UTC, lin-brian-l requested changes
@dbhynds great work! I have some minor comments but things look good so far.

2023-12-04 22:43 UTC, lin-brian-l commented on src/LtiMessageLaunch.php
> +            $this->setRequest($request);
`!isset()` can mean that the variable is `null` or `undefined`; does the case of `undefined` need to be addressed?

2023-12-05 16:13 UTC, dbhynds commented on .githooks/pre-commit
> +function fail_if_on_master_branch {
I don't think so, cos if someone forks the repo, they'd be working on the master branch of their fork

2023-12-05 16:31 UTC, lin-brian-l requested changes
@dbhynds I've got one last question about the githook!

2023-12-05 16:31 UTC, lin-brian-l commented on .githooks/pre-commit
> +function fail_if_on_master_branch {
@dbhynds sounds good, can this function be deleted if it's not being used then?

2023-12-05 17:27 UTC, lin-brian-l submitted a review, later dismissed

2023-12-05 19:41 UTC, lin-brian-l approved these changes

2023-12-05 19:44 UTC, merged