Include resourceLinkId attribute when creating line item
packbackbooks/lti-1-3-php-library pull request #36
Opened 2021-11-02 03:08 UTC by mattwright

## Summary of Changes

Resource link id was not being sent in requests to create a line item. You can see that this field is documented here:

https://www.imsglobal.org/spec/lti-ags/v2p0#resourcelinkid-and-binding-a-line-item-to-a-resource-link
https://canvas.instructure.com/doc/api/line_items.html

## Testing

Manual testing in Canvas LMS

2021-11-02 18:56 UTC, dbhynds requested changes
Great catch! Would you mind updating the `LtiLineitemTest::testItCastsFullObjectToString()` to ensure this value gets set when it gets passed in, so we don't make this mistake again?

2021-11-03 05:32 UTC, mattwright commented
Yep, I’ll look into the test code when I’m next at my computer.

2021-11-04 06:17 UTC, mattwright commented
OK, I added the test -- thanks for pointing me in the right direction.

2021-11-04 13:05 UTC, dbhynds approved these changes

2021-11-04 13:11 UTC, merged